### ISSUE TITLE
Google Charts API is deprecated and not available since March 19, 2019

### ISSUE THREAD

**Issue by olenichphp** [sonata-project/GoogleAuthenticator#136]
## Subject
Problem with getting QR code from https://chart.googleapis.com/chart?

## Actual results
502 error

###  Warning notes from  https://developers.google.com/chart/image/
> Warning: This API is deprecated and is scheduled to be turned off on March 14, 2019. Please use the actively maintained Google Charts API instead.

**Comment by core23** [comment]
Can you provide a PR with a fix @olenichphp ?

**Comment by jgaranae** [comment]
I'm experiment this issue too. But I don't find how to fix it. Any ideas?

**Comment by anomis66** [comment]
I have also experience this error.  The Google / Charts / Image API is deprecated and generates a '502 - Bad Gateway' error when attempting to generate a QR code with the API.  IMHO, an alternate QR code generation is needed.

**Comment by olenichphp** [comment]
@core23 yes I've a PR with fix. But I can't push. 
For fix just replace  src/GoogleQrUrl.php:86:
`'https://api.qrserver.com/v1/create-qr-code/?size=%1$dx%1$d&data=%2$s&ecc=M'`

**Comment by netniV** [comment]
I have created and submitted a PR based solely on the recommendation above.

**Comment by netniV** [comment]
Also, this bug should not be unconfirmed as Google themselves are notifying visitors to their webiste:
![image](https://user-images.githubusercontent.com/9052188/54683412-86cecf00-4b09-11e9-9322-9db2f926845b.png)

**Comment by OskarStark** [comment]
Thank you, I removed the corresponding label 👍
