### ISSUE TITLE
Fix Comment on Discrepancy

### ISSUE THREAD

**Issue by fiedsch** [sonata-project/GoogleAuthenticator#148]
## Subject

The Comment on Discrepancy in https://github.com/sonata-project/GoogleAuthenticator/blob/2.x/src/GoogleAuthenticator.php#L75-L78 seems wrong: 

30 seconds before and after 10:00:00 should be `09:59:30` (as in comment) to `10:00:29` (which is `10:01:29` in the comment).

**Comment by core23** [comment]
Can you provide a PR with a fix @fiedsch

**Comment by fiedsch** [comment]
Will do so tomorrow.
