### ISSUE TITLE
How can I create the secret code in random form?

### ISSUE THREAD

**Issue by netwons** [sonata-project/GoogleAuthenticator#172]
my point is $secret = "XVQ2UIGO75XRUKJO";

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
