### ISSUE TITLE
Replay-protection 

### ISSUE THREAD

**Issue by omexlu** [sonata-project/GoogleAuthenticator#177]
What's missing in the example:
Prevent replay attacks. One token should only be used once

How this can be done?

**Comment by core23** [comment]
Is this a feature request or a general question?

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help

**Comment by omexlu** [comment]
It's both of them :)

**Comment by VincentLanglet** [comment]
I'm closing this since the package is deprecated/abandoned.
