### ISSUE TITLE
Code on App is different than code generated by $g->getcode();

### ISSUE THREAD

**Issue by Ab-Nexttech** [sonata-project/GoogleAuthenticator#182]
I successfully generate the QR code, but i can’t validate it with the function $g->checkCode().when I tried to show code its different than code on app .
this is my code to check the code typed by the user:
$g = new \Google\Authenticator\GoogleAuthenticator();
      $secret =$_POST['secret'];
      $user = base64_decode($_GET['u']);

      $user_data=explode(',',$user);
      $check_this_code = $_POST['code'];
      if ($g->checkCode($secret, $check_this_code)) {
          echo 'Success!';
      } else {
          echo 'Invalid login';
      }
can you help me?

**Comment by HermanRas** [comment]
I have same problem, only using example file. running version 2.2.0 latest

**Comment by HermanRas** [comment]
> I have same problem, only using example file. running version 2.2.0 latest
the server time was wrong.. fixed for me after updating daylight savings settings!

**Comment by OskarStark** [comment]
Thanks for coming back and share the solution 👍

**Comment by wadelzubair** [comment]
same problem here

**Comment by HermanRas** [comment]
> same problem here

The problem was fixed changing the timezone in php.ini file to a UTC+2 region where DST has never been observed (Africa/Johannesburg) 

Please see PHP TimeZone's here [PHP DateTime](https://www.php.net/manual/en/timezones.php)

**Comment by VincentLanglet** [comment]
I'm closing this since the package is deprecated/abandoned.
