### ISSUE TITLE
Fatal error: Uncaught Error: Interface 'Sonata\GoogleAuthenticator\GoogleAuthenticatorInterface' not found in

### ISSUE THREAD

**Issue by smalos** [sonata-project/GoogleAuthenticator#187]
Example.php shows an error:

Fatal error: Uncaught Error: Interface 'Sonata\GoogleAuthenticator\GoogleAuthenticatorInterface' not found in 'GoogleAuthenticator\src\GoogleAuthenticator.php'

I fixed it by adding

`include_once __DIR__.'/../src/GoogleAuthenticatorInterface.php';`

Important: Order of includes:

```
include_once __DIR__.'/../src/FixedBitNotation.php';
include_once __DIR__.'/../src/GoogleAuthenticatorInterface.php';
include_once __DIR__.'/../src/GoogleAuthenticator.php';
include_once __DIR__.'/../src/GoogleQrUrl.php';
```

in example.php.

Same issue in sample\web\index.php

**Comment by BGmot** [comment]
The same issue with simple web server example at sample/web/index.php

**Comment by VincentLanglet** [comment]
I'm closing this since the package is deprecated/abandoned.
