### ISSUE TITLE
PHP8?

### ISSUE THREAD

**Issue by omexlu** [sonata-project/GoogleAuthenticator#236]
Hello,

I wanted to ask if the current version is compatible with PHP8 and if not for when that is expected to be the case?

Thanks in advance.

**Comment by VincentLanglet** [comment]
Our php 8 tests are green so I think it basically just need a PR to allow php 8 in the composer.json.

Do you want to do it @omexlu ? :)

**Comment by omexlu** [comment]
Thanks but i leave the pleasure some else to PR this :)
