### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by dalibor-sojic** [sonata-project/GoogleAuthenticator#288]
`
        $otpauthString = rawurlencode(sprintf($otpauthString, $label, $secret, $issuer));

        return sprintf(
            'https://api.qrserver.com/v1/create-qr-code/?size=%1$dx%1$d&data=%2$s&ecc=M',
            $size,
            $otpauthString
        ); `

Showing QR code by passing $secret to external service, visible in URL is a serious security issue. 

Consider implementing https://medium.com/ampersand-academy/generate-qr-code-using-php-b4d13a9ed8dd

**Comment by core23** [comment]
Can you provide a PR @dalibor-sojic ?

**Comment by dalibor-sojic** [comment]
Soon

**Comment by VincentLanglet** [comment]
I'm closing this since the package is deprecated/abandoned.
