### ISSUE TITLE
Bad class api - GoogleAuthenticator

### ISSUE THREAD

**Issue by nepster-web** [sonata-project/GoogleAuthenticator#289]
So, I found problem where qr code doesn't work on iphone. 

If we increase **secretLength** to 32 length, then an example of secrets would be like this: 
`ZPOSJX4VJXYWB3Z7Y67IDXXRB57H5T2XY4S2PI3VXQPBWZQB7HBA====`

This will work for android, but symbol "=" doesn't like iphone.

I have no way to extend the class GoogleAuthenticator that to change it.

**Comment by VincentLanglet** [comment]
I'm closing this since the package is deprecated/abandoned.
