### ISSUE TITLE
Have PHP and PowerShell create the same PIN

### ISSUE THREAD

**Issue by cabozone** [sonata-project/GoogleAuthenticator#299]
## Feature Request

I am creating an API for an application and I am using your GoogleAuth 2.x PHP to generate the Secret and then the PIN,   I am then using a library for PowerShell to call the URL using a PowerShell GoogleAuth library with the Same secret.  the PIN's that are created are different.  Is there a setting or feature to make them the same from the same secret?

PowerShell Library https://github.com/HumanEquivalentUnit/PowerShell-Misc/blob/master/GoogleAuthenticator.psm1

Get-GoogleAuthenticatorPin -Secret 'DB2EAFQFOV34V4P'  
PS PIN = 790763
PHP PIN  = 997898

**Comment by VincentLanglet** [comment]
I'm closing this since the package is deprecated/abandoned.
