### ISSUE TITLE
This bundle is abandoned // Looking for maintainers

### ISSUE THREAD

**Issue by core23** [sonata-project/GoogleAuthenticator#309]
This project has some technical design issues and critical bugs.

Since no sonata-maintainer is using this project, there is no active support on this bundle.
That's why we will be marked it as abandoned.

Feel free to ask if you want to keep this project up to date.

**Comment by fracz** [comment]
One can safely replace this library with e.g. https://github.com/RobThree/TwoFactorAuth that is being maintained.

**Comment by fylzero** [comment]
I replaced this with...
https://github.com/pragmarx/google2fa
https://github.com/antonioribeiro/google2fa

This is what Laravel Jetstream uses for it's 2FA.  It would be nice convenience to add this as a recommended replacement on Packagist.
