### ISSUE TITLE
Backup codes?

### ISSUE THREAD

**Issue by ahmeds63** [sonata-project/GoogleAuthenticator#316]
Many sites are providing backup codes facility in case user has no access to their mobile device for example they have lost their device etc.. in that case backup codes are really helpful. Can we have them please?

**Comment by core23** [comment]
> Can we have them please?

Sure. Feel free to do this by providing a Pull Request 👍

**Comment by VincentLanglet** [comment]
I'm closing this since the package is deprecated/abandoned.
