### ISSUE TITLE
Code from app and getCode not match

### ISSUE THREAD

**Issue by RASTecnoTI** [sonata-project/GoogleAuthenticator#320]
I used the example.php file and worked fine, thw qr code has been generatted but dont match the codes. 

I already chech the time zone and server time / date and is fine.

What do I have to do now?

**Comment by RASTecnoTI** [comment]
This is my test file https://office.beercoin.app/test.php

**Comment by downdijk** [comment]
Since today i have the same problem. The code worked all year untill today, so whats changed on Google's code?
I hope you can find a fix.

**Comment by jordisala1991** [comment]
This library is lacking good maintenance, do you want to help us?

**Comment by downdijk** [comment]
I need to dive in deeper into the code first to understand whats happening and im a bit short on time atm, but i can check whats going wrong.

**Comment by downdijk** [comment]
Update: Seems it didnt work because my server time was out of sync that causes the problems

**Comment by VincentLanglet** [comment]
I'm closing this since the package is deprecated/abandoned.
